#### The sinking of the Titanic is one of the most horrific  event in history.It led to the loss of  over 1000 lives. Reseachers  have since been piqued by the reasons behind the tragic loss of lives despite being well equiped with safety equipments.

#### In this  research project I am going to use decision  tree  to determine variables that influenced the chances of survival in the titanic.

In [46]:
#load standard libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [47]:
#load the dataset
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [48]:
#calculating correlation between survival and number of siblings
corr = df[['Survived', "SibSp"]].corr()
corr

          Survived     SibSp
Survived  1.000000 -0.035322
SibSp    -0.035322  1.000000

In [49]:
corr = df[['Survived', "Fare"]].corr()
corr

          Survived      Fare
Survived  1.000000  0.257307
Fare      0.257307  1.000000

In [50]:
features = df[["Pclass", "Sex", "Age","Fare" ]]

In [81]:
features.head(2)

   Pclass  Sex  Age     Fare
0       3    1   28   7.2500
1       1    0   52  71.2833

In [62]:
target = df['Survived']

In [52]:
features.isnull()

     Pclass    Sex    Age   Fare
0     False  False  False  False
1     False  False  False  False
2     False  False  False  False
3     False  False  False  False
4     False  False  False  False
..      ...    ...    ...    ...
886   False  False  False  False
887   False  False  False  False
888   False  False   True  False
889   False  False  False  False
890   False  False  False  False

[891 rows x 4 columns]

In [57]:
mean_value = features['Age'].mean()
mean_value

29.69911764705882

In [54]:
print(features["Sex"].dtype)

object

In [55]:
print(features["Age"].dtype)

float64

In [59]:
features["Age"]

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [58]:

features['Age'].fillna(value=mean_value, inplace=True)

C:\Users\UCHIHA MADARA\AppData\Local\Temp\ipykernel_1152\4015002673.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features['Age'].fillna(value=mean_value, inplace=True)

In [61]:
features["Age"].isnull

<bound method Series.isnull of 0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64>

In [64]:
features.head()

   Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [65]:
from sklearn.preprocessing import LabelEncoder

In [66]:
sex_enc = LabelEncoder()

In [69]:
features["Sex"] = sex_enc.fit_transform(features["Sex"])

C:\Users\UCHIHA MADARA\AppData\Local\Temp\ipykernel_1152\280969372.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features["Sex"] = sex_enc.fit_transform(features["Sex"])

In [70]:
features

     Pclass  Sex  Age     Fare
0         3    1   28   7.2500
1         1    0   52  71.2833
2         3    0   34   7.9250
3         1    0   48  53.1000
4         3    1   48   8.0500
..      ...  ...  ...      ...
886       2    1   35  13.0000
887       1    0   24  30.0000
888       3    0   39  23.4500
889       1    1   34  30.0000
890       3    1   43   7.7500

[891 rows x 4 columns]

In [71]:
features.head()

   Pclass  Sex  Age     Fare
0       3    1   28   7.2500
1       1    0   52  71.2833
2       3    0   34   7.9250
3       1    0   48  53.1000
4       3    1   48   8.0500

In [74]:
X = features

In [75]:
y= target

In [76]:
from sklearn import tree

In [77]:
model = tree.DecisionTreeClassifier()

In [73]:
from sklearn.model_selection import train_test_split

In [78]:
X_train,X_test, y_train, y_test =  train_test_split(X, y, train_size=0.2)

In [79]:
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [80]:
model.score(X_train, y_train)

0.9943820224719101

99% accuracy. The model is working great